export const DISTRICT_MANDALS = {
  Adilabad: [
    "Adilabad Rural",
    "Adilabad Urban",
    "Bazarhatnoor",
    "Bela",
    "Bheempoor",
    "Boath",
    "Gadiguda",
    "Gudihathnur",
    "Ichoda",
    "Inderavelly",
    "Jainad",
    "Mavala",
    "Narnoor",
    "Neradigonda",
    "Sirikonda",
    "Talamadagu",
    "Tamsi",
    "Utnoor",
  ],
  "Bhadradri Kothagudem": [
    "Allapalli",
    "Annapureddypally",
    "Aswapuram",
    "Aswaraopeta",
    "Bhadrachalam",
    "Burgampahad",
    "Chandrugonda",
    "Cherla",
    "Chunchupally",
    "Dammapeta",
    "Dummugudem",
    "Gundala",
    "Julurpad",
    "Karakagudem",
    "Kothagudem",
    "Laxmidevipalli",
    "Manuguru",
    "Mulakalapalle",
    "Palvancha",
    "Pinapaka",
    "Sujathanagar",
    "Tekulapalle",
    "Yellandu",
  ],
  Hanamkonda: [
    "Atmakur",
    "Bheemadevarapalle",
    "Damera",
    "Dharmasagar",
    "Elkathurthy",
    "Hanamkonda",
    "Hasanparthy",
    "Inavole",
    "Kamalapur",
    "Kazipet",
    "Nadikuda",
    "Parkal",
    "Shayampet",
    "Velair",
  ],
  Hyderabad: [
    "Amberpet",
    "Ameerpet",
    "Asif Nagar",
    "Bahadurpura",
    "Bandlaguda",
    "Charminar",
    "Golkonda",
    "Himayathnagar",
    "Khairtabad",
    "Maredpally",
    "Musheerabad",
    "Nampally",
    "Saidabad",
    "Secunderabad",
    "Shaikpet",
    "Tirumalgiri",
  ],
  Jagtial: [
    "Beerpur",
    "Bheemaram",
    "Buggaram",
    "Dharmapuri",
    "Endapally",
    "Gollapalle",
    "Ibrahimpatnam",
    "Jagtial",
    "Jagtial Rural",
    "Kathlapur",
    "Kodimial",
    "Korutla",
    "Mallapur",
    "Mallial",
    "Medipalle",
    "Metpalli",
    "Pegadapalle",
    "Raikal",
    "Sarangapur",
    "Velgatoor",
  ],
  Jangaon: [
    "Bachannapeta",
    "Chilpur",
    "Devaruppala",
    "Jangaon",
    "Kodakandla",
    "Lingalaghanpur",
    "Narmetta",
    "Palakurthi",
    "Raghunathapalle",
    "Station Ghanpur",
    "Tharigoppula",
    "Zaffergadh",
  ],
  "Jayashankar Bhupalpally": [
    "Bhupalpalle",
    "Chityal",
    "Ghanpur",
    "Kataram",
    "Mahadevpur",
    "Maha Mutharam",
    "Malharrao",
    "Mogullapalle",
    "Palimela",
    "Regonda",
    "Tekumatla",
  ],
  "Jogulamba Gadwal": [
    "Aiza",
    "Alampur",
    "Dharur",
    "Gadwal",
    "Ghattu",
    "Itikyal",
    "Kaloor Timmanadoddi",
    "Maldakal",
    "Manopad",
    "Rajoli",
    "Undavelli",
    "Waddepalle",
  ],
  Kamareddy: [
    "Banswada",
    "Bhiknoor",
    "Bibipet",
    "Bichkunda",
    "Birkoor",
    "Domakonda",
    "Dongli",
    "Gandhari",
    "Jukkal",
    "Kamareddy",
    "Lingampet",
    "Machareddy",
    "Madnur",
    "Naga Reddipet",
    "Nasurullabad",
    "Nizamsagar",
    "Pedda Kodapgal",
    "Pitlam",
    "Rajampet",
    "Ramareddy",
    "Sadasivanagar",
    "Tadwai",
    "Yellareddy",
  ],
  Karimnagar: [
    "Chigurumamidi",
    "Choppadandi",
    "Ellandakunta",
    "Gangadhara",
    "Ganneruvaram",
    "Huzurabad",
    "Jammikunta",
    "Karimnagar",
    "Karimnagar Rural",
    "Kothapalli",
    "Manakondur",
    "Ramadugu",
    "Shankarapatnam",
    "Thimmapur",
    "V. Saidapur",
    "Veenavanka",
  ],
  Khammam: [
    "Bonakal",
    "Chinthakani",
    "Enkuru",
    "Kalluru",
    "Kamepalle",
    "Khammam Rural",
    "Khammam Urban",
    "Konijerla",
    "Kusumanchi",
    "Madhira",
    "Mudigonda",
    "Nelakondapalle",
    "Penuballi",
    "Raghunadhapalem",
    "Sathupalli",
    "Singareni",
    "Thallada",
    "Thirumalayapalem",
    "Vemsoor",
    "Wyra",
    "Yerrupalem",
  ],
  "Komaram Bheem Asifabad": [
    "Asifabad",
    "Bejjur",
    "Chintalamanepally",
    "Dahegaon",
    "Jainoor",
    "Kagaznagar",
    "Kerameri",
    "Kouthala",
    "Lingapur",
    "Penchikalpet",
    "Rebbena",
    "Sirpur (T)",
    "Sirpur (U)",
    "Tiryani",
    "Wankidi",
  ],
  Mahabubabad: [
    "Bayyaram",
    "Chinnagudur",
    "Danthalapalle",
    "Dornakal",
    "Garla",
    "Gudur",
    "Inugurthy",
    "Kesamudram",
    "Kothaguda",
    "Kuravi",
    "Mahabubabad",
    "Maripeda",
    "Narsimhulapet",
    "Nellikudur",
    "Peddavangara",
    "Thorrur",
  ],
  Mahabubnagar: [
    "Addakal",
    "Balanagar",
    "Bhoothpur",
    "Chinna Chinta Kunta",
    "Devarkadara",
    "Gandeed",
    "Hanwada",
    "Jadcherla",
    "Koilkonda",
    "Mahabubnagar Rural",
    "Mahabubnagar Urban",
    "Midjil",
    "Mohammadabad",
    "Musapet",
    "Nawabpet",
    "Rajapur",
  ],
  Mancherial: [
    "Bellampally",
    "Bheemaram",
    "Bheemini",
    "Chennur",
    "Dandepally",
    "Hajipur",
    "Jaipur",
    "Jannaram",
    "Kannepally",
    "Kasipet",
    "Kotapally",
    "Luxettipet",
    "Mancherial",
    "Mandamarri",
    "Naspur",
    "Nennel",
    "Tandur",
    "Vemanpally",
  ],
  Medak: [
    "Alladurg",
    "Chegunta",
    "Chilipched",
    "Havelighanpur",
    "Kowdipalle",
    "Kulcharam",
    "Manoharabad",
    "Masaipet",
    "Medak",
    "Narsapur",
    "Narsingi",
    "Nizampet",
    "Papannapet",
    "Ramayampet",
    "Regode",
    "Shankarampet (A)",
    "Shankarampet (R)",
    "Shivampet",
    "Tekmal",
    "Tupran",
    "Yeldurthy",
  ],
  "Medchal-Malkajgiri": [
    "Alwal",
    "Bachupally",
    "Balanagar",
    "Dundigal Gandimaisamma",
    "Ghatkesar",
    "Kapra",
    "Keesara",
    "Kukatpally",
    "Malkajgiri",
    "Medchal",
    "Medipally",
    "Muduchintalpalli",
    "Quthbullapur",
    "Shamirpet",
    "Uppal",
  ],
  Mulugu: [
    "Eturnagaram",
    "Govindaraopet",
    "Kannaigudem",
    "Mangapet",
    "Mulugu",
    "Tadvai",
    "Venkatapur",
    "Venkatapuram",
    "Wazeed",
  ],
  Nagarkurnool: [
    "Achampet",
    "Amrabad",
    "Balmoor",
    "Bijinapalle",
    "Charakonda",
    "Kalwakurthy",
    "Kodair",
    "Kollapur",
    "Lingal",
    "Nagarkurnool",
    "Padra",
    "Peddakothapalle",
    "Pentlavelli",
    "Tadoor",
    "Telkapalle",
    "Thimmajipeta",
    "Uppunuthala",
    "Urkonda",
    "Vangoor",
    "Veldanda",
  ],
  Nalgonda: [
    "Adavi Devulapalli",
    "Anumula",
    "Chandampet",
    "Chandur",
    "Chinthapalle",
    "Chityal",
    "Damaracherla",
    "Devarakonda",
    "Gundlapalle",
    "Gurrampode",
    "Kanagal",
    "Kattangoor",
    "Kethepally",
    "Kondamallapally",
    "Madugulapally",
    "Marriguda",
    "Miryalaguda",
    "Munugode",
    "Nakrekal",
    "Nalgonda",
    "Nampalle",
    "Narayanapur",
    "Neredugommu",
    "Nidamanur",
    "Pedda Adiserlapalle",
    "Peddavoora",
    "Shaligauraram",
    "Thipparthi",
    "Thripuraram",
    "Tirumalagiri Sagar",
    "Vemulapalle",
  ],
  Narayanpet: [
    "Damaragidda",
    "Dhanwada",
    "Kosgi",
    "Krishna",
    "Maddur",
    "Maganoor",
    "Makthal",
    "Marikal",
    "Narayanpet",
    "Narva",
    "Utkoor",
  ],
  Nirmal: [
    "Basar",
    "Bhainsa",
    "Dilawarpur",
    "Kadam",
    "Khanapur",
    "Kubeer",
    "Kuntala",
    "Laxmanchanda",
    "Lokeswaram",
    "Mamda",
    "Mudhole",
    "Narsapur (G)",
    "Nirmal Rural",
    "Nirmal Urban",
    "Pembi",
    "Sarangapur",
    "Soan",
    "Tanur",
  ],
  Nizamabad: [
    "Armoor",
    "Balkonda",
    "Bheemgal",
    "Bodhan",
    "Chandur",
    "Dharpally",
    "Dichpalli",
    "Indalwai",
    "Jakranpalli",
    "Kammarpally",
    "Kotgiri",
    "Makloor",
    "Mendora",
    "Morthad",
    "Mosra",
    "Mugpal",
    "Navipet",
    "Nizamabad North",
    "Nizamabad Rural",
    "Nizamabad South",
    "Nizamabad Urban",
    "Ranjal",
    "Rudrur",
    "Sirikonda",
    "Velpur",
    "Varni",
    "Yedpally",
    "Yeragatla",
  ],
  Peddapalli: [
    "Antargaon",
    "Anantharam",
    "Eligaid",
    "Julapalli",
    "Kamanpur",
    "Dharmaram",
    "Manthani",
    "Mutharam",
    "Odela",
    "Palakurthi",
    "Peddapalli",
    "Ramagiri",
    "Ramagundam",
    "Sultanabad",
  ],
  "Rajanna Sircilla": [
    "Boinpalle",
    "Chandurthi",
    "Ghambiraopet",
    "Illanthakunta",
    "Konaraopet",
    "Mustabad",
    "Rudrangi",
    "Sircilla",
    "Thangallapalli",
    "Veernapalli",
    "Vemulawada",
    "Vemulawada Rural",
    "Yellareddypet",
  ],
  Rangareddy: [
    "Abdullapurmet",
    "Amangal",
    "Balapur",
    "Chevella",
    "Chowdergudem",
    "Farooqnagar",
    "Gachibowli",
    "Gandipet",
    "Hayathnagar",
    "Ibrahimpatnam",
    "Kadthal",
    "Keshampet",
    "Kondurg",
    "Kothur",
    "Madgul",
    "Maheshwaram",
    "Manchal",
    "Moinabad",
    "Nandigama",
    "Rajendranagar",
    "Serilingampally",
    "Shabad",
    "Shamshabad",
    "Shankarpalle",
    "Talakondapally",
    "Yacharam",
  ],
  Sangareddy: [
    "Ameenpur",
    "Andole",
    "Gummadidala",
    "Hathnoora",
    "Jharasangam",
    "Jinnaram",
    "Kalher",
    "Kandi",
    "Kangti",
    "Karasgutty",
    "Kohir",
    "Kondapur",
    "Manoor",
    "Munipally",
    "Nagalgidda",
    "Narayankhed",
    "Nyalkal",
    "Patancheru",
    "Pulkal",
    "Ramachandrapuram",
    "Sadasivpet",
    "Sangareddy",
    "Sirgapoor",
    "Vatpally",
    "Zaheerabad",
  ],
  Siddipet: [
    "Akkannapet",
    "Bejjanki",
    "Cherial",
    "Chinnakodur",
    "Doultabad",
    "Dubbak",
    "Gajwel",
    "Husnabad",
    "Jagdevpur",
    "Koheda",
    "Komuravelli",
    "Kondapak",
    "Maddur",
    "Markook",
    "Mirdoddi",
    "Mulug",
    "Nangnoor",
    "Raipole",
    "Siddipet Rural",
    "Siddipet Urban",
    "Toguta",
    "Wargal",
  ],
  Suryapet: [
    "Ananthagiri",
    "Atmakur (S)",
    "Chilkur",
    "Chivvemla",
    "Garidepalle",
    "Huzurnagar",
    "Jajireddygudem",
    "Kodad",
    "Maddirala",
    "Mallareddygudem",
    "Mattampally",
    "Mellachervu",
    "Mothey",
    "Munagala",
    "Nadigudem",
    "Nereducherla",
    "Nuthankal",
    "Palakeedu",
    "Penpahad",
    "Suryapet",
    "Thirumalagiri",
    "Tungathurthi",
  ],
  Vikarabad: [
    "Bantwaram",
    "Bashirabad",
    "Bomraspet",
    "Dharur",
    "Doma",
    "Doulatabad",
    "Kodangal",
    "Kotepally",
    "Kulkacharla",
    "Marpalle",
    "Mominpet",
    "Nawabpet",
    "Pargi",
    "Peddemul",
    "Pudur",
    "Tandur",
    "Vikarabad",
    "Yalal",
  ],
  Wanaparthy: [
    "Amarchinta",
    "Atmakur",
    "Chinnambavi",
    "Ghanpur",
    "Gopalpeta",
    "Kothakota",
    "Madanapur",
    "Pangal",
    "Pebbair",
    "Peddamandadi",
    "Revally",
    "Srirangapur",
    "Wanaparthy",
    "Weepangandla",
  ],
  Warangal: [
    "Chennaraopet",
    "Duggondi",
    "Geesugonda",
    "Khila Warangal",
    "Khanapur",
    "Nallabelli",
    "Narsampet",
    "Nekkonda",
    "Parvathagiri",
    "Rayaparthy",
    "Sangem",
    "Wardhannapet",
  ],
  "Yadadri Bhuvanagiri": [
    "Addagudur",
    "Alair",
    "Atmakur (M)",
    "Bhongir",
    "Bibinagar",
    "Bhoodan Pochampally",
    "Bommalaramaram",
    "Choutuppal",
    "Gundala",
    "Motakondur",
    "Narayanpur",
    "Rajapet",
    "Ramannapet",
    "Turkapally",
    "Valigonda",
    "Yadagirigutta",
  ],
} as const;

export type District = keyof typeof DISTRICT_MANDALS;
export type Mandal = (typeof DISTRICT_MANDALS)[District][number];
