/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GrievanceRouteImport } from './routes/grievance'
import { Route as OperatorRouteImport } from './routes/operator'
import { Route as QrRouteImport } from './routes/qr'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as TrainerAnalyticsRouteImport } from './routes/trainer.analytics'
import { Route as TrainerDashboardRouteImport } from './routes/trainer.dashboard'
import { Route as TrainerLoginRouteImport } from './routes/trainer.login'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRoute = GrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorRoute = OperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerAnalyticsRoute = TrainerAnalyticsRouteImport.update({
  id: '/trainer/analytics',
  path: '/trainer/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerDashboardRoute = TrainerDashboardRouteImport.update({
  id: '/trainer/dashboard',
  path: '/trainer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerLoginRoute = TrainerLoginRouteImport.update({
  id: '/trainer/login',
  path: '/trainer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grievance': typeof GrievanceRoute
  '/operator': typeof OperatorRoute
  '/qr': typeof QrRoute
  '/track': typeof TrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/staff/login': typeof StaffLoginRoute
  '/trainer/analytics': typeof TrainerAnalyticsRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/trainer/login': typeof TrainerLoginRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grievance': typeof GrievanceRoute
  '/operator': typeof OperatorRoute
  '/qr': typeof QrRoute
  '/track': typeof TrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/staff/login': typeof StaffLoginRoute
  '/trainer/analytics': typeof TrainerAnalyticsRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/trainer/login': typeof TrainerLoginRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grievance': typeof GrievanceRoute
  '/operator': typeof OperatorRoute
  '/qr': typeof QrRoute
  '/track': typeof TrackRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/staff/login': typeof StaffLoginRoute
  '/trainer/analytics': typeof TrainerAnalyticsRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/trainer/login': typeof TrainerLoginRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grievance'
    | '/operator'
    | '/qr'
    | '/track'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/login'
    | '/staff/login'
    | '/trainer/analytics'
    | '/trainer/dashboard'
    | '/trainer/login'
    | '/api/public/bootstrap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/grievance'
    | '/operator'
    | '/qr'
    | '/track'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/login'
    | '/staff/login'
    | '/trainer/analytics'
    | '/trainer/dashboard'
    | '/trainer/login'
    | '/api/public/bootstrap'
  id:
    | '__root__'
    | '/'
    | '/grievance'
    | '/operator'
    | '/qr'
    | '/track'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/login'
    | '/staff/login'
    | '/trainer/analytics'
    | '/trainer/dashboard'
    | '/trainer/login'
    | '/api/public/bootstrap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GrievanceRoute: typeof GrievanceRoute
  OperatorRoute: typeof OperatorRoute
  QrRoute: typeof QrRoute
  TrackRoute: typeof TrackRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  StaffLoginRoute: typeof StaffLoginRoute
  TrainerAnalyticsRoute: typeof TrainerAnalyticsRoute
  TrainerDashboardRoute: typeof TrainerDashboardRoute
  TrainerLoginRoute: typeof TrainerLoginRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance': {
      id: '/grievance'
      path: '/grievance'
      fullPath: '/grievance'
      preLoaderRoute: typeof GrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator': {
      id: '/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof OperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/analytics': {
      id: '/trainer/analytics'
      path: '/trainer/analytics'
      fullPath: '/trainer/analytics'
      preLoaderRoute: typeof TrainerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/dashboard': {
      id: '/trainer/dashboard'
      path: '/trainer/dashboard'
      fullPath: '/trainer/dashboard'
      preLoaderRoute: typeof TrainerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/login': {
      id: '/trainer/login'
      path: '/trainer/login'
      fullPath: '/trainer/login'
      preLoaderRoute: typeof TrainerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GrievanceRoute: GrievanceRoute,
  OperatorRoute: OperatorRoute,
  QrRoute: QrRoute,
  TrackRoute: TrackRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  StaffLoginRoute: StaffLoginRoute,
  TrainerAnalyticsRoute: TrainerAnalyticsRoute,
  TrainerDashboardRoute: TrainerDashboardRoute,
  TrainerLoginRoute: TrainerLoginRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
